### create a new patient entity
POST http://localhost:4004/patients
Content-Type: application/json
Authorization: Bearer {{token}}
Host: lb-e5d9ccc0.elb.localhost.localstack.cloud

{
   "name" : "maow7" ,
   "email" : "maow7@gmail.com" ,
   "address" : "2257 st main" ,
   "dateOfBirth" : "1999-01-11" ,
   "registeredDate" : "2025-08-06"
}

###